routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PrincipalController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PrincipalController::class, 'principalBaterias'])->name('/');

Route::get('/teoria', [PrincipalController::class, 'teoria'])->name('teoria');

Route::get('/procedimento', [PrincipalController::class, 'procedimento'])->name('procedimento');

Route::get('/medicoes', [PrincipalController::class, 'medicoes'])->name('medicoes');

Route::get('/conclusoes', [PrincipalController::class, 'conclusoes'])->name('conclusoes');

Route::get('/principal', [PrincipalController::class, 'principal']);

Route::get('/pagina1', [PrincipalController::class, 'pagina1']);

Route::get('/pagina2', [PrincipalController::class, 'pagina2']);

app/Models/Medicoes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicoes extends Model
{
    use HasFactory;

    public function getResistenciaInternaAttribute()
    {
       return $this->resistencia_carga * ($this->tensao_sem_carga /$this->tensao_com_carga-1);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Medicoes;

class PrincipalController extends Controller {

    public function principalBaterias(){
        return view('principalBaterias');
    }

    public function teoria(){
        return view('teoria');
    }

    public function procedimento(){
        return view('procedimento');
    }

    public function medicoes(){
        $medicoes = Medicoes::all();
        return view('medicoes', compact('medicoes'));
    }

    public function conclusoes(){
        return view('conclusoes');
    }

    public function principal(){
        return view('principal');
    }

    public function pagina1() {
        return view('pagina1');
    }

    public function pagina2() {
        return view('pagina2');
    }

}

resources/views/conclusoes.blade.php
@extends ('templates.base')

@section('conteudo')
    <main>
        <h1>Conclusões</h1>
        <hr>
        <h3>Pilhas/Baterias</h3>
        <h5>Com os valores de resistência interna das pilhas e baterias podemos perceber quais delas estão carregadas ou descarregadas. Caso essa resistência seja alta, podemos concluir que a pilhas está ao fim de sua vida útil. Por outro lado, caso a resistência esteja baixa, indica-se que a pilha ainda está utilizável.</h5>
        <p></p>
        <p>A bateria Elgin é a bateria com maior resistência interna, ou seja, a que está mais descarregada, mesmo sendo recarregável sua resistência já é extremamente alta, isso quer dizer que sua vida útil já chegou ao fim.</p>
        <img src="../imgs/bateriaelgin.jpeg" alt="Bateria Elgin" height="200">
        <p></p>
        <p>A bateria Golite e a pilha Duracell Plus AAA também têm suas resistências internas altas, indicando que seus tempos de utilização já terminaram.</p>
        <img src="../imgs/golite.jpeg" alt="Bateria Golite" height="200"><img src="../imgs/duracellaaa.jpeg" alt="Pilha Duracell AAA" height="200">
        <p></p>
        <p>Já as pilhas que estão carregadas e que podem ser utilizadas ainda são aquelas as quais possuem baixa resistência interna, as pilhas medidas que estão mais próprias para uso são:</p>
        <img src="../imgs/duracellAA.jpeg" alt="Pilha Duracell AA">
        <p>Duracell AA</p>
        <img src="../imgs/freedom.jpeg" alt="Bateria Freedom" height="200">
        <p>Bateria Freedom</p>
        <hr>
        <h3>Conclusão Geral</h3>
        <h5>Com o trabalho conseguimos maximizar nossas habilidades e conhecimentos sobre as matérias Programação em Automação e Eletroeletrônica. Foi possível aplicar os conhecimentos teóricos sobre HTML, CSS e JavaScript fazendo o relatório. Além disso, montar a folha de estilos colocou nossa criatividade em exercício, o código HTML ajudou-nos a aplicar os nossos conhecimentos e a parte do JavaScript foi útil para podermos aprender um pouco mais sobre essa linguagem.
            Em relação à Eletroeletrônica conseguimos colocar em prática nossos conhecimentos por meio das medições e dos cálculos de resistência interna das pilhas e baterias.
        No geral, pensamos que esse trabalho tem alto valor acadêmico e que vai ajudar muito na nossa formação em técnicos de automação industrial.  </h5>
    </main>
    @endsection

@section('rodape')
<h10>Rodape das Conclusões </h10>
@endsection

resources/views/medicoes.blade.php
@extends('templates.base')

@section('conteudo')
<main>
    <h1>Medições</h1>
    <hr>
    <h2>Valores obtidos:</h2>
    <table class="table table-striped table-bordered" id="tbDados">
        <thead>
            <tr>
                <th>Pilha/Bateria</th>
                <th>Tensão nominal (V)</th>
                <th>Capacidade de corrente (mA.h)</th>
                <th>Tensão sem carga(V)</th>
                <th>Tensão com carga(V)</th>
                <th>Resitência de carga(ohm)</th>
                <th>Resistência interna(ohm)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($medicoes as $medicao)
            <tr>
                <td>{{$medicao->pilha_bateria}}</td>
                <td>{{number_format($medicao->tensao_nominal,1,'.','')}}</td>
                <td>{{$medicao->capacidade_corrente}}</td>
                <td>{{$medicao->tensao_sem_carga}}</td>
                <td>{{$medicao->tensao_com_carga}}</td>
                <td>{{$medicao->resistencia_carga}}</td>
                <td>{{number_format($medicao->resistencia_interna,3,'.','')}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</main>
@endsection

@section('rodape')
<h4>Rodapé Medições</h4>
@endsection

resources/views/pagina1.blade.php
@extends ("templates.base")
@section ("conteudo")
<h2>Pagina1</h2>
<hr>
@endsection

@section ("rodape")
<hr>
<h4>Rodape da pagina1</h4>
@endsection

resources/views/pagina2.blade.php
@extends ("templates.base")
@section ("conteudo")
<h2>Pagina2</h2>
<hr>
@endsection

@section ("rodape")
<hr>
<h4>Rodape da pagina2</h4>
@endsection

resources/views/principal.blade.php
@extends ("templates.base")
@section ("conteudo")
<h2>Pagina Principal</h2>
<hr>
@endsection

@section ("rodape")
<hr>
<h4>Rodape da pagina pricipal</h4>
@endsection

resources/views/principalBaterias.blade.php
@extends ('templates.base')

@section('conteudo')
    <main>
        <h1>Turma: 2D3 - Grupo 4</h1>
        <h2>Participantes:</h2>
        <table class="table table-dark table-striped table-bordered">
            <tr>
                <th>Matricula</th>
                <th>Nome</th>
                <th>Função</th>
            </tr>
            <tr>
                <td>0072556</td>
                <td>Pedro Augusto de Paiva Costa</td>
                <td>Gerente e Desenvolvedor HTML</td>
            </tr>
            <tr>
                <td>0072552</td>
                <td>Matias Dias Bezerra Oliveira Caetano</td>
                <td>Desenvolvedor CSS e JavaScript</td>
            </tr>
            <tr>
                <td>0072544</td>
                <td>Pedro Vitor da Silva Freitas</td>
                <td>Medições</td>
            </tr>
            <tr>
                <td>0066591</td>
                <td>Kemuel Victor dos Santos Quirino</td>
                <td>Medições</td>
            </tr>
        </table>
        <img src="imgs/grupo.jpeg" alt="Alunos do Grupo" height="240">
    </main>
@endsection

@section('rodape')
<h6>Rodape da pagina pricipal </h6>
@endsection

resources/views/procedimento.blade.php
@extends ('templates.base')

@section('conteudo')
    <main>
        <h1>Procedimento</h1>
        <hr>
        <h2>Medição:</h2>
        <p>1. Medição do valor do resistor utilizando o multímetro na escala de ohms (Ω);</p>
        <p>2. Medição da tensão real de todas as pilhas utilizando o multímetro na escala de tensão (V);</p>
        <p>3. Medição da tensão com carga das pilhas, ligando-as ao resistor e medindo com o multímetro na escala de tensão (V);</p>
        <p>4. Registramos no caderno os resultados obtidos, os quais foram utilizados para formar a tabela da página "Medições".</p>
        <p></p>
        <h2>Materiais utilizados:</h2>
        <h4>Multímetro:</h4>
        <img src="../imgs/multimetro.jpeg" alt="Multímetro" height="200">
        <p></p>
        <h4>Pilhas/Baterias:</h4>
        <img src="../imgs/1-destinacao-de-residuos-perigosos.jpg" alt="Pilhas/Baterias" height="200">
        <p></p>
        <h4>Resistor:</h4>
        <img src="../imgs/resistor.jpeg" alt="Resistor" height="200">
        <p></p>
        <p>*imagens ilustrativas</p>
    </main>
    @endsection

@section('rodape')
<h6>Rodape da pagina Procedimento </h6>
@endsection

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bateriasaravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/estilos.css') }}">
</head>

<body>
    <div class="container-md">
        <h1>Baterias Laravel</h1>
        <hr>
        <nav>
            <ul>
                <li><a href="{{ route('/') }}">Início</a></li>
                <li><a href="{{ route('teoria') }}">Teoria</a></li>
                <li><a href="{{ route('procedimento') }}">Procedimento</a></li>
                <li><a href="{{ route('medicoes') }}">Medições</a></li>
                <li><a href="{{ route('conclusoes') }}">Conclusões</a></li>
            </ul>
        </nav>

        @yield("conteudo")
        <div class="rodape container-md">
            @yield("rodape")
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

resources/views/teoria.blade.php
@extends ('templates.base')

@section('conteudo')
    <main>
        <h1>Teoria</h1>
        <hr>
        <h2>Resistência interna de uma fonte:</h2>
        <p> Uma fonte de tensão real é constituída de uma fonte de tensão ideal (E) em série com a sua resistência interna (r) como mostra o circuito abaixo:</p>
        <img src="../imgs/fonte-real.png" alt="Fonte Real">
        <p>Para conhecermos o valor da tensão interna da fonte (E) basta medirmos diretamente essa fonte com um multímetro desde que não haja nenhuma carga ligada a essa fonte:</p>
        <img src="../imgs/fonte-real (1).png" alt="Medição tensão interna">  
        <p>Quando conectamos uma carga (R) a essa fonte, circulará uma corrente (I) que produzirá queda de tensão interna (Vr) e a queda de tensão externa (VR):</p>
        <img src="../imgs/f2.png" alt="Conexão de carga">  
        <p>A equação para encontrarmos a equação interna, já simplificada é:</p>
        <img src="../imgs/Equacao.png" alt="Equação">
        <hr>
        <h2>O que são Pilhas/Baterias</h2>
        <p>Pilhas e baterias são dispositivos eletroquímicos usados para fornecer energia elétrica em aparelhos eletrônicos, dispositivos portáteis e uma ampla gama de equipamentos. Embora frequentemente sejam mencionados juntos, eles têm algumas diferenças importantes.</p>

            <h5>Pilhas:</h5> 
            <p>Uma pilha é um dispositivo eletroquímico simples, geralmente cilíndrico ou em formato de disco, composto por dois eletrodos (um positivo e um negativo) e um eletrólito que separa os eletrodos. O eletrólito é uma substância condutora de íons. Os eletrodos são feitos de materiais específicos, como zinco e manganês, que reagem quimicamente com o eletrólito para produzir energia elétrica.</p>
            
            <p>Quando um circuito elétrico é conectado aos terminais da pilha, ocorrem reações eletroquímicas nos eletrodos e no eletrólito, resultando em uma corrente elétrica que flui através do circuito. Conforme a reação química ocorre, os materiais nos eletrodos se esgotam, e a energia fornecida pela pilha diminui até que a pilha esteja completamente descarregada e pare de produzir energia. As pilhas primárias são projetadas para uso único e não são recarregáveis.</p> 
            
            <h5>Baterias:</h5>
            <p>Uma bateria, por outro lado, é composta por um ou mais elementos individuais (células) conectados em série ou paralelo para aumentar a tensão ou a capacidade da energia fornecida. As baterias podem ser feitas usando tecnologia semelhante à das pilhas, mas têm uma construção mais complexa e geralmente contêm várias células em um único invólucro. Elas podem ser recarregáveis, o que significa que, depois de esgotarem sua energia, podem ser recarregadas conectando-as a uma fonte de energia externa, revertendo as reações eletroquímicas e restaurando a energia da bateria.</p> 
            
            <p>As baterias recarregáveis são amplamente usadas em dispositivos eletrônicos, veículos elétricos, sistemas de armazenamento de energia e muito mais. Elas oferecem a vantagem de serem reutilizáveis, reduzindo o desperdício em comparação com as pilhas primárias, que são descartadas após o uso.</p> 
    </main>
    @endsection

@section('rodape')

<h6>Rodape da pagina Teoria</h6>

@endsection